version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py

    volumes:
      - .:/app
    ports:
      - '5000:5000'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env


volumes:
  postgres-data:
    driver: local
